name: Build cmd

on: [push, pull_request]

jobs:

  test-windows:
    name: Test for Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    env:
      OS: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-toolchain mingw-w64-x86_64-sqlite3
          msystem: MINGW64
          path-type: inherit

      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: 
          go-version-file: ./go.mod 
          cache: true

      - run: go version

      - name: Add $GOPATH/bin to $PATH
        run: |
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
        shell: msys2 {0}


      - name: Install dependencies
        run: go get ./...        
        shell: msys2 {0}

      - name: 'Build'
        run: go build -v ./...
        shell: msys2 {0}

      - name: 'Test'
        run: go test -v ./...
        shell: msys2 {0}

  test-posix:
    name: Test MacOS/Ubuntu
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    env:
      OS: ${{ matrix.os }}
    steps:
      - if: startsWith(matrix.os, 'macos')
        run: brew update

      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: 
          go-version-file: ./go.mod 
          cache: true

      - name: Add $GOPATH/bin to $PATH
        run: |
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"


      - name: Install dependencies
        run: go get ./...        

      - name: 'Build'
        run: go build -v ./...

      - name: 'Test'
        run: go test -v ./...

