name: Build and Publish Releases

#on:
#  release:
#    types: [created]

on: [push, pull_request]

jobs:
  build-windows:
    name: Windows Binaries
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-toolchain mingw-w64-x86_64-sqlite3
          msystem: MINGW64
          path-type: inherit

      - uses: actions/setup-go@v3
        with: 
          go-version: 1.19 
          cache: true

      - name: Add $GOPATH/bin to $PATH
        run: |
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
        shell: msys2 {0}

      - run: go env
        shell: msys2 {0}

      - uses: actions/checkout@v3   

      - name: Install dependencies
        run: go get ./...        
        shell: msys2 {0}

      #- name: Version
      #  run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}

      - name: Build 
        run: go build -v -ldflags "-X main.app_ver=v0.1.0" .
        shell: msys2 {0}

      - name: Check
        run: ls
        

  build-macos:
    name: MacOS Binaries
    runs-on: macos-latest
    steps:
      - run: brew update

      - uses: actions/setup-go@v3
        with: 
          go-version: 1.19 
          cache: true

      - name: Add $GOPATH/bin to $PATH
        run: |
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - run: go env

      - uses: actions/checkout@v3   

      - name: Install dependencies
        run: go get ./...        

      - name: Version
        run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}

      - name: Build 
        run: go build -v -ldflags "-X main.app_ver=v0.1.0" .

      - name: Check
        run: ls

  build-linux:
    name: Linux Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with: 
          go-version: 1.19 
          cache: true

      - name: Add $GOPATH/bin to $PATH
        run: |
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - run: go env

      - uses: actions/checkout@v3   

      - name: Install dependencies
        run: go get ./...        

      - name: Version
        run: echo APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) >> ${GITHUB_ENV}

      - name: Build 
        run: go build -v -ldflags "-X main.app_ver=v0.1.0" .

      - name: Check
        run: ls

